cmake_minimum_required(VERSION 3.30)
project(CoreLayer)

set(CMAKE_CXX_STANDARD 23)

add_executable(CoreLayer main.cpp
        PCH.h
        include/publicCore/Model.h
        src/Model.tpp
        src/OdeSolver/ODESolver.cpp
        src/OdeSolver/ODESolver.h
        src/OdeSolver/RungeKutta4Solver/RungeKutta4Solver.cpp
        src/OdeSolver/RungeKutta4Solver/RungeKutta4Solver.h
        src/DynamicsSystem/IDynamicsSystem.cpp
        src/DynamicsSystem/IDynamicsSystem.h
        src/DynamicsSystem/FullRocketODE/FullRocketODE.cpp
        src/DynamicsSystem/FullRocketODE/FullRocketODE.h
        src/WorldModel/AbstractWorldModel.h
        src/WorldModel/WorldComponents/WindModel/IWindModel.h
        src/WorldModel/WorldComponents/WindModel/NoWindModel/NoWindModel.tpp
        src/WorldModel/WorldComponents/WindModel/NoWindModel/NoWindModel.h
        src/WorldModel/ConcreteWorld/SimpleWorld/SimpleWorld.tpp
        src/WorldModel/ConcreteWorld/SimpleWorld/SimpleWorld.h
        src/WorldModel/WorldComponents/AtmosphericModel/IAtmosphericModel.h
        src/WorldModel/WorldComponents/AtmosphericModel/SimpleAtmosphericModel/AtmosphericModel.tpp
        src/WorldModel/WorldComponents/AtmosphericModel/SimpleAtmosphericModel/AtmosphericModel.h
        CONSTANTS.h
        src/WorldModel/WorldComponents/GravityModel/IGravitationalModel.h
        src/WorldModel/WorldComponents/GravityModel/KavendishModel/KavendishModel.tpp
        src/WorldModel/WorldComponents/GravityModel/KavendishModel/KavendishModel.h
        src/WorldModel/WorldComponents/CoriolisModel/ICoriolisModel.h
        src/WorldModel/WorldComponents/CoriolisModel/NoCoriolisForceModel/NoCoriolisForceModel.tpp
        src/WorldModel/WorldComponents/CoriolisModel/NoCoriolisForceModel/NoCoriolisForceModel.h
        src/WorldModel/WorldComponents/ITerrainModel/ITerrainModel.h
        src/WorldModel/WorldComponents/ITerrainModel/PlaneTerrain/PlaneTerrain.tpp
        src/WorldModel/WorldComponents/ITerrainModel/PlaneTerrain/PlaneTerrain.h
        src/PhysicalObjects/Target/Target.cpp
        src/PhysicalObjects/Target/Target.h
        src/PhysicalObjects/Target/SimpleTarget/SimpleTarget.cpp
        src/PhysicalObjects/Target/SimpleTarget/SimpleTarget.h
        src/PhysicalObjects/Aircraft/AbstractAircraft.cpp
        src/PhysicalObjects/Aircraft/AbstractAircraft.h
        src/SimulationMomento/SimulationMomento.cpp
        src/SimulationMomento/SimulationMomento.h
        src/utils/ObjSnapshot.h
        src/SimulationMomento/SaveStrategy/SaveStrategy.cpp
        src/SimulationMomento/SaveStrategy/SaveStrategy.h
        src/SimulationMomento/StateStorage.h
        src/PhysicalObjects/RandomObject/RandomObject.cpp
        src/PhysicalObjects/RandomObject/RandomObject.h
        src/PhysicalObjects/AbstractObject.cpp
        src/PhysicalObjects/AbstractObject.h
        src/PhysicalObjects/Aircraft/Missle/GuidedMissle/MANPADS/V1/MANPAD_V1.cpp
        src/PhysicalObjects/Aircraft/Missle/GuidedMissle/MANPADS/V1/MANPAD_V1.h
        src/DynamicsSystem/ExtensionModels/Aerodinamics/FullModel/FullModel.cpp
        src/DynamicsSystem/ExtensionModels/Aerodinamics/FullModel/FullModel.h
        src/DynamicsSystem/ExtensionModels/Aerodinamics/AeroInput/AeroInput.cpp
        src/DynamicsSystem/ExtensionModels/Aerodinamics/AeroInput/AeroInput.h
        src/utils/ObjInitParams.h
        GLOBAL_CONFIG.h
        src/PhysicalObjects/ObjectManager.cpp
        src/PhysicalObjects/ObjectManager.h
        src/utils/SimulationDescriber.h
        src/utils/ContinuationCallback.h
        src/utils/Interpolation/Interpolator/IInterpolator.h
        "src/utils/Interpolation/IBilinearInterpolator /IBilinearInterpolator.h"
        src/utils/Interpolation/Interpolator/LinearInterpolator/LinearInterpolator.cpp
        src/utils/Interpolation/Interpolator/LinearInterpolator/LinearInterpolator.h
        src/utils/Interpolation/IBilinearInterpolator/BilinearInterpolator/BilinearInterpolator.cpp
        src/utils/Interpolation/IBilinearInterpolator/BilinearInterpolator/BilinearInterpolator.h
        src/utils/DataTable/IDataTable2D/DataTable2D.h
        src/utils/DataTable/IDataTable1D/IDataTable1D.h
        src/utils/DataTable/IDataTable1D/DataTable1D_fromCSV/DataTable1D_fromCSV.cpp
        src/utils/DataTable/IDataTable1D/DataTable1D_fromCSV/DataTable1D_fromCSV.h
)
